-- Generated by db-subset-agent (OpenRouter tool calling)
BEGIN;
CREATE SCHEMA IF NOT EXISTS "subset";
SET LOCAL statement_timeout = '0';
SET LOCAL lock_timeout = '0';

-- 1) Temporary selection sets (PKs)
CREATE TEMP TABLE "_sel_users" ("id" INTEGER PRIMARY KEY);
CREATE TEMP TABLE "_sel_products" ("id" INTEGER PRIMARY KEY);
CREATE TEMP TABLE "_sel_orders" ("id" INTEGER PRIMARY KEY);

-- 2) Seed anchors (LLM-selected PK queries)
INSERT INTO "_sel_users" ("id")
SELECT id FROM users ORDER BY random()
ON CONFLICT DO NOTHING;

INSERT INTO "_sel_products" ("id")
SELECT id FROM products ORDER BY random()
ON CONFLICT DO NOTHING;

INSERT INTO "_sel_orders" ("id")
SELECT id FROM orders ORDER BY random() LIMIT 800
ON CONFLICT DO NOTHING;


-- 3) Expand selection sets to keep relations (bounded)
-- Iteration 1/2
-- Upward: orders.product_id -> products.id
INSERT INTO "_sel_products" ("id")
SELECT DISTINCT c."product_id" AS "id"
FROM "main"."orders" c
JOIN "_sel_orders" sc ON c."id" = sc."id"
LEFT JOIN "_sel_products" sp ON sp."id" = c."product_id"
WHERE c."product_id" IS NOT NULL AND sp."id" IS NULL
LIMIT 20
ON CONFLICT DO NOTHING;

-- Upward: orders.user_id -> users.id
INSERT INTO "_sel_users" ("id")
SELECT DISTINCT c."user_id" AS "id"
FROM "main"."orders" c
JOIN "_sel_orders" sc ON c."id" = sc."id"
LEFT JOIN "_sel_users" sp ON sp."id" = c."user_id"
WHERE c."user_id" IS NOT NULL AND sp."id" IS NULL
LIMIT 100
ON CONFLICT DO NOTHING;

-- Downward: pick up to 5 orders rows per selected products
WITH candidates AS (
  SELECT c."id" AS "id",         row_number() OVER (PARTITION BY c."product_id" ORDER BY random()) AS rn
  FROM "main"."orders" c
  JOIN "_sel_products" sp ON c."product_id" = sp."id"
), picked AS (
  SELECT "id" FROM candidates WHERE rn <= 5
)
INSERT INTO "_sel_orders" ("id")
SELECT "id" FROM picked
LIMIT 800
ON CONFLICT DO NOTHING;

-- Downward: pick up to 5 orders rows per selected users
WITH candidates AS (
  SELECT c."id" AS "id",         row_number() OVER (PARTITION BY c."user_id" ORDER BY random()) AS rn
  FROM "main"."orders" c
  JOIN "_sel_users" sp ON c."user_id" = sp."id"
), picked AS (
  SELECT "id" FROM candidates WHERE rn <= 5
)
INSERT INTO "_sel_orders" ("id")
SELECT "id" FROM picked
LIMIT 800
ON CONFLICT DO NOTHING;

-- Iteration 2/2
-- Upward: orders.product_id -> products.id
INSERT INTO "_sel_products" ("id")
SELECT DISTINCT c."product_id" AS "id"
FROM "main"."orders" c
JOIN "_sel_orders" sc ON c."id" = sc."id"
LEFT JOIN "_sel_products" sp ON sp."id" = c."product_id"
WHERE c."product_id" IS NOT NULL AND sp."id" IS NULL
LIMIT 20
ON CONFLICT DO NOTHING;

-- Upward: orders.user_id -> users.id
INSERT INTO "_sel_users" ("id")
SELECT DISTINCT c."user_id" AS "id"
FROM "main"."orders" c
JOIN "_sel_orders" sc ON c."id" = sc."id"
LEFT JOIN "_sel_users" sp ON sp."id" = c."user_id"
WHERE c."user_id" IS NOT NULL AND sp."id" IS NULL
LIMIT 100
ON CONFLICT DO NOTHING;

-- Downward: pick up to 5 orders rows per selected products
WITH candidates AS (
  SELECT c."id" AS "id",         row_number() OVER (PARTITION BY c."product_id" ORDER BY random()) AS rn
  FROM "main"."orders" c
  JOIN "_sel_products" sp ON c."product_id" = sp."id"
), picked AS (
  SELECT "id" FROM candidates WHERE rn <= 5
)
INSERT INTO "_sel_orders" ("id")
SELECT "id" FROM picked
LIMIT 800
ON CONFLICT DO NOTHING;

-- Downward: pick up to 5 orders rows per selected users
WITH candidates AS (
  SELECT c."id" AS "id",         row_number() OVER (PARTITION BY c."user_id" ORDER BY random()) AS rn
  FROM "main"."orders" c
  JOIN "_sel_users" sp ON c."user_id" = sp."id"
), picked AS (
  SELECT "id" FROM candidates WHERE rn <= 5
)
INSERT INTO "_sel_orders" ("id")
SELECT "id" FROM picked
LIMIT 800
ON CONFLICT DO NOTHING;


-- 4) Materialize subset schema (tables, then data)

DROP TABLE IF EXISTS "users_subset";
CREATE TABLE "users_subset" AS
SELECT t.* FROM "users" t
JOIN "_sel_users" s ON t."id" = s."id";

DROP TABLE IF EXISTS "products_subset";
CREATE TABLE "products_subset" AS
SELECT t.* FROM "products" t
JOIN "_sel_products" s ON t."id" = s."id";

DROP TABLE IF EXISTS "orders_subset";
CREATE TABLE "orders_subset" AS
SELECT t.* FROM "orders" t
JOIN "_sel_orders" s ON t."id" = s."id";

-- 5) (Optional) Add foreign keys back in subset schema if you want them.
--     This script does not recreate FKs automatically (keeps it simple + avoids cycles).
COMMIT;
