from typing import Any, Dict, List

from .utils import qi


def build_subset_sql(
    schema_obj: Dict[str, Any],
    plan: Dict[str, Any],
    subset_schema: str = "subset",
) -> str:
    """
    Generate the final SQL script based on the LLM's plan.
    The plan is now a list of steps: [{"comment": "...", "sql": "..."}]
    """
    engine = str(schema_obj.get("engine", "postgres")).lower()
    steps = plan.get("steps", [])

    lines: List[str] = []
    lines.append("-- Generated by db-subset-agent")
    lines.append("-- This script assumes the target schema already exists (tables created) and is empty.")
    lines.append("")

    if "postgres" in engine:
        lines.append("BEGIN;")
        lines.append(f"CREATE SCHEMA IF NOT EXISTS {qi(subset_schema)};")
        lines.append("SET LOCAL statement_timeout = '0';")
        lines.append("SET LOCAL lock_timeout = '0';")
        lines.append("SET session_replication_role = 'replica'; -- Disable triggers/FKs for data load")
        lines.append("")
    else:
        # SQLite
        lines.append("PRAGMA foreign_keys = OFF;")
        lines.append("BEGIN TRANSACTION;")
        lines.append("")

    for i, step in enumerate(steps):
        comment = step.get("comment", "")
        sql = step.get("sql", "").strip()
        if comment:
            lines.append(f"-- Step {i+1}: {comment}")
        
        # Security check (basic)
        if not sql:
            continue
            
        # Ensure the SQL ends with semicolon
        if not sql.endswith(";"):
            sql += ";"
            
        lines.append(sql)
        lines.append("")

    lines.append("-- Commit and Restore")
    if "postgres" in engine:
        lines.append("SET session_replication_role = 'origin';")
        lines.append("COMMIT;")
    else:
        lines.append("COMMIT;")
        lines.append("PRAGMA foreign_keys = ON;")
    lines.append("")

    return "\n".join(lines)
