from typing import Any, Dict, List, Tuple
from .utils import qi, qname, SQL_READONLY_PREFIX, SQL_FORBIDDEN

def build_subset_sql(
    schema_obj: Dict[str, Any],
    plan: Dict[str, Any],
    subset_schema: str = "subset",
) -> str:
    tables = schema_obj["tables"]

    # map table -> pk (single-col only, for now)
    pk1: Dict[Tuple[str, str], Tuple[str, str]] = {}  # (schema, table) -> (pk_col, pk_type)
    coltypes: Dict[Tuple[str, str, str], str] = {}    # (schema, table, col) -> type

    for t in tables:
        sch, name = t["schema"], t["name"]
        for c in t["columns"]:
            coltypes[(sch, name, c["name"])] = c["type"]
        if len(t["primary_key"]) == 1:
            pkcol = t["primary_key"][0]
            pktype = coltypes.get((sch, name, pkcol), "text")
            pk1[(sch, name)] = (pkcol, pktype)

    # anchors from plan
    anchors = plan.get("anchors", [])
    iterations = int(plan.get("iterations", 2))
    max_children_per_fk = int(plan.get("max_children_per_fk", 5))
    table_caps = plan.get("table_caps", {})  # optional dict: table->cap

    lines: List[str] = []
    lines.append("-- Generated by db-subset-agent (OpenRouter tool calling)")
    lines.append("BEGIN;")
    lines.append(f"CREATE SCHEMA IF NOT EXISTS {qi(subset_schema)};")
    lines.append("SET LOCAL statement_timeout = '0';")
    lines.append("SET LOCAL lock_timeout = '0';")
    lines.append("")

    # temp selection tables
    lines.append("-- 1) Temporary selection sets (PKs)")
    for (sch, tname), (pkcol, pktype) in pk1.items():
        lines.append(f"CREATE TEMP TABLE {qi('_sel_' + tname)} ({qi(pkcol)} {pktype} PRIMARY KEY);")
    lines.append("")

    # apply anchors
    lines.append("-- 2) Seed anchors (LLM-selected PK queries)")
    for a in anchors:
        tname = a["table"]
        sel_sql = a["select_pk_sql"].strip()
        if not SQL_READONLY_PREFIX.search(sel_sql) or SQL_FORBIDDEN.search(sel_sql) or ";" in sel_sql.rstrip(";"):
            raise ValueError(f"Anchor select_pk_sql for table={tname} is not a safe single SELECT/WITH/EXPLAIN")
        
        # try to find by table name
        found = False
        for (sch, tn), info in pk1.items():
            if tn == tname:
                pkcol, _pktype = info
                found = True
                lines.append(f"INSERT INTO {qi('_sel_' + tname)} ({qi(pkcol)})")
                lines.append(f"{sel_sql}")
                lines.append("ON CONFLICT DO NOTHING;")
                lines.append("")
                break
        if not found:
            lines.append(f"-- Skipping anchor {tname}: no single-column PK detected.")
        continue
    lines.append("")

    # build FK list for expansion (single-col FK -> single-col PK only)
    fk_edges: List[Tuple[str, str, str, str, str, str]] = []  # child_sch, child_table, child_pk, fk_col, parent_sch, parent_table
    for t in tables:
        c_sch, child = t["schema"], t["name"]
        if (c_sch, child) not in pk1:
            continue
        child_pk, _ = pk1[(c_sch, child)]
        for fk in t["foreign_keys"]:
            cols = fk["columns"]
            p_sch = fk["ref_schema"]
            parent = fk["ref_table"]
            ref_cols = fk["ref_columns"]
            if len(cols) == 1 and len(ref_cols) == 1 and (p_sch, parent) in pk1:
                # assume ref col is the PK col (common case); otherwise we still can do upward inclusion by ref col
                fk_edges.append((c_sch, child, child_pk, cols[0], p_sch, parent))

    # expansion loops
    lines.append("-- 3) Expand selection sets to keep relations (bounded)")
    for it in range(iterations):
        lines.append(f"-- Iteration {it+1}/{iterations}")

        # upward closure: include parents referenced by selected children
        for c_sch, child, child_pk, fk_col, p_sch, parent in fk_edges:
            parent_pk, _ = pk1[(p_sch, parent)]
            cap = table_caps.get(parent)
            cap_clause = f"LIMIT {int(cap)}" if cap else ""
            lines.append(f"-- Upward: {child}.{fk_col} -> {parent}.{parent_pk}")
            lines.append(f"INSERT INTO {qi('_sel_' + parent)} ({qi(parent_pk)})")
            lines.append("SELECT DISTINCT c.{fk} AS {p_pk}".format(
                fk=qi(fk_col),
                p_pk=qi(parent_pk),
            ))
            lines.append(f"FROM {qname(c_sch, child)} c")
            lines.append(f"JOIN {qi('_sel_' + child)} sc ON c.{qi(child_pk)} = sc.{qi(child_pk)}")
            lines.append(f"LEFT JOIN {qi('_sel_' + parent)} sp ON sp.{qi(parent_pk)} = c.{qi(fk_col)}")
            lines.append(f"WHERE c.{qi(fk_col)} IS NOT NULL AND sp.{qi(parent_pk)} IS NULL")
            if cap_clause:
                lines.append(cap_clause)
            lines.append("ON CONFLICT DO NOTHING;")
            lines.append("")

        # downward: include a few children per selected parent (for test coverage)
        for c_sch, child, child_pk, fk_col, p_sch, parent in fk_edges:
            child_cap = table_caps.get(child)
            child_cap_clause = f"LIMIT {int(child_cap)}" if child_cap else ""
            parent_pk, _ = pk1[(p_sch, parent)]
            lines.append(f"-- Downward: pick up to {max_children_per_fk} {child} rows per selected {parent}")
            lines.append("WITH candidates AS (")
            lines.append(
                f"  SELECT c.{qi(child_pk)} AS {qi(child_pk)},"
                f"         row_number() OVER (PARTITION BY c.{qi(fk_col)} ORDER BY random()) AS rn"
            )
            lines.append(f"  FROM {qname(c_sch, child)} c")
            lines.append(f"  JOIN {qi('_sel_' + parent)} sp ON c.{qi(fk_col)} = sp.{qi(parent_pk)}")
            lines.append("), picked AS (")
            lines.append(f"  SELECT {qi(child_pk)} FROM candidates WHERE rn <= {max_children_per_fk}")
            lines.append(")")
            lines.append(f"INSERT INTO {qi('_sel_' + child)} ({qi(child_pk)})")
            lines.append(f"SELECT {qi(child_pk)} FROM picked")
            if child_cap_clause:
                lines.append(child_cap_clause)
            lines.append("ON CONFLICT DO NOTHING;")
            lines.append("")

    lines.append("")

    # materialize subset schema tables
    lines.append("-- 4) Materialize subset schema (tables, then data)")
    if "postgres" in str(schema_obj.get("engine", "")).lower():
        lines.append(f"CREATE SCHEMA IF NOT EXISTS {qi(subset_schema)};")
    lines.append("")
    for (sch, tname), (pkcol, _pktype) in pk1.items():
        if "postgres" in str(schema_obj.get("engine", "")).lower():
            # Note: CREATE TABLE ... LIKE doesn't copy foreign keys; CHECK constraints + PK/UNIQUE via INCLUDING INDEXES.
            lines.append(f"DROP TABLE IF EXISTS {qname(subset_schema, tname)} CASCADE;")
            lines.append(
                f"CREATE TABLE {qname(subset_schema, tname)} "
                f"(LIKE {qname(sch, tname)} INCLUDING CONSTRAINTS INCLUDING INDEXES INCLUDING COMMENTS);"
            )
            lines.append(
                f"INSERT INTO {qname(subset_schema, tname)} "
                f"SELECT t.* FROM {qname(sch, tname)} t "
                f"JOIN {qi('_sel_' + tname)} s ON t.{qi(pkcol)} = s.{qi(pkcol)};"
            )
        else:
            # SQLite or generic
            lines.append(f"DROP TABLE IF EXISTS {qi(tname + '_subset')};")
            lines.append(f"CREATE TABLE {qi(tname + '_subset')} AS")
            lines.append(f"SELECT t.* FROM {qi(tname)} t")
            lines.append(f"JOIN {qi('_sel_' + tname)} s ON t.{qi(pkcol)} = s.{qi(pkcol)};")
        lines.append("")

    lines.append("-- 5) (Optional) Add foreign keys back in subset schema if you want them.")
    lines.append("--     This script does not recreate FKs automatically (keeps it simple + avoids cycles).")
    lines.append("COMMIT;")
    lines.append("")

    return "\n".join(lines)
